worker_processes auto;

events {
    worker_connections 1024;
}

http {
    # Definir upstreams para cada servicio
    upstream register_service {
        server auth-register-service:3001;
    }

    upstream login_service {
        server auth-login-service:3002;
    }

    upstream profile_service {
        server auth-profile-service:3003;
    }

    upstream password_service {
        server auth-password-service:3004;
    }

    upstream logout_service {
        server auth-logout-service:3005;
    }

    upstream history_service {
        server auth-history-service:3006;
    }

    server {
        listen 80;
        server_name localhost;

        # Configuración común para todos los servicios
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Ruta para el servicio de registro
        location /register {
            proxy_pass http://register_service;
        }

        # Ruta para el servicio de inicio de sesión
        location /login {
            proxy_pass http://login_service;
        }

        # Ruta para el servicio de perfil
        location /profile {
            proxy_pass http://profile_service;
        }

        # Ruta para el servicio de contraseña
        location /password {
            proxy_pass http://password_service;
        }

        # Ruta para el servicio de cierre de sesión
        location /logout {
            proxy_pass http://logout_service;
        }

        location /history {
            proxy_pass http://auth-history-service:9292;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
